// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShakyFruits.Data;

#nullable disable

namespace ShakyFruits.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260827050738_AddLifetimeStatsToAccount")]
    partial class AddLifetimeStatsToAccount
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FruitAssetFruitType", b =>
                {
                    b.Property<int>("FruitAssetsId")
                        .HasColumnType("int");

                    b.Property<int>("FruitsInImageId")
                        .HasColumnType("int");

                    b.HasKey("FruitAssetsId", "FruitsInImageId");

                    b.HasIndex("FruitsInImageId");

                    b.ToTable("FruitAssetFruitType");
                });

            modelBuilder.Entity("ShakyFruits.Core.Entities.AccountAnalyticsHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EstimatedRewards")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FollowingCount")
                        .HasColumnType("int");

                    b.Property<int>("LifetimeLikes")
                        .HasColumnType("int");

                    b.Property<int>("ProfileViews")
                        .HasColumnType("int");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalComments")
                        .HasColumnType("int");

                    b.Property<int>("TotalFollowers")
                        .HasColumnType("int");

                    b.Property<int>("TotalLikes")
                        .HasColumnType("int");

                    b.Property<int>("TotalShares")
                        .HasColumnType("int");

                    b.Property<int>("TotalVideoViews")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("AccountAnalyticsHistory");
                });

            modelBuilder.Entity("ShakyFruits.Core.Entities.DailyTrend", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Platform")
                        .HasColumnType("int");

                    b.Property<DateTime>("TrendDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrendType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("ViewCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("DailyTrends");
                });

            modelBuilder.Entity("ShakyFruits.Core.Entities.FruitAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMultipleFruits")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("FruitAssets");
                });

            modelBuilder.Entity("ShakyFruits.Core.Entities.FruitType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("FruitTypes");
                });

            modelBuilder.Entity("ShakyFruits.Core.Entities.PublishedVideo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Platform")
                        .HasColumnType("int");

                    b.Property<string>("PostUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("VideoGenerationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VideoGenerationId");

                    b.ToTable("PublishedVideos");
                });

            modelBuilder.Entity("ShakyFruits.Core.Entities.ReferenceVideo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DanceStyle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KlingSourceUrlOrId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SourceType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VideoPath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ReferenceVideos");
                });

            modelBuilder.Entity("ShakyFruits.Core.Entities.VideoAnalytics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Comments")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Favorites")
                        .HasColumnType("int");

                    b.Property<int>("Likes")
                        .HasColumnType("int");

                    b.Property<int>("PublishedVideoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Shares")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Views")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PublishedVideoId");

                    b.ToTable("VideoAnalytics");
                });

            modelBuilder.Entity("ShakyFruits.Core.Entities.VideoGeneration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AiGeneratedCaption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AppliedPrompt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FruitAssetId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRecreate")
                        .HasColumnType("bit");

                    b.Property<string>("OutputVideoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReferenceVideoId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetResolution")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FruitAssetId");

                    b.HasIndex("ReferenceVideoId");

                    b.ToTable("VideoGenerations");
                });

            modelBuilder.Entity("FruitAssetFruitType", b =>
                {
                    b.HasOne("ShakyFruits.Core.Entities.FruitAsset", null)
                        .WithMany()
                        .HasForeignKey("FruitAssetsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShakyFruits.Core.Entities.FruitType", null)
                        .WithMany()
                        .HasForeignKey("FruitsInImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShakyFruits.Core.Entities.PublishedVideo", b =>
                {
                    b.HasOne("ShakyFruits.Core.Entities.VideoGeneration", "VideoGeneration")
                        .WithMany()
                        .HasForeignKey("VideoGenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VideoGeneration");
                });

            modelBuilder.Entity("ShakyFruits.Core.Entities.VideoAnalytics", b =>
                {
                    b.HasOne("ShakyFruits.Core.Entities.PublishedVideo", "PublishedVideo")
                        .WithMany("AnalyticsHistory")
                        .HasForeignKey("PublishedVideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PublishedVideo");
                });

            modelBuilder.Entity("ShakyFruits.Core.Entities.VideoGeneration", b =>
                {
                    b.HasOne("ShakyFruits.Core.Entities.FruitAsset", "FruitAsset")
                        .WithMany("Generations")
                        .HasForeignKey("FruitAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShakyFruits.Core.Entities.ReferenceVideo", "ReferenceVideo")
                        .WithMany("Generations")
                        .HasForeignKey("ReferenceVideoId");

                    b.Navigation("FruitAsset");

                    b.Navigation("ReferenceVideo");
                });

            modelBuilder.Entity("ShakyFruits.Core.Entities.FruitAsset", b =>
                {
                    b.Navigation("Generations");
                });

            modelBuilder.Entity("ShakyFruits.Core.Entities.PublishedVideo", b =>
                {
                    b.Navigation("AnalyticsHistory");
                });

            modelBuilder.Entity("ShakyFruits.Core.Entities.ReferenceVideo", b =>
                {
                    b.Navigation("Generations");
                });
#pragma warning restore 612, 618
        }
    }
}
